version: 2
updates:
  # Infra.
  - package-ecosystem: "terraform"
    directory: "/infra"
    schedule:
      interval: "weekly"

  # CI.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
